version: "3"
services:

  maven:
    image: maven:3.5.3-jdk-8-slim
    volumes:
      - /home/env/.m2:/root/.m2
    network_mode: "host"

  gradle:
    image: gradle:4.6.0-jdk8
    network_mode: "host"
